/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "rgb(var(--primary))",
          inverse: "rgb(var(--primary-inverse))",
          hover: "rgb(var(--primary-hover))",
          active: "rgb(var(--primary-active-color))",
          highlight: "rgb(var(--primary)/var(--primary-highlight-opacity))",
          "highlight-inverse": "rgb(var(--primary-highlight-inverse))",
          "highlight-hover":
            "rgb(var(--primary)/var(--primary-highlight-hover-opacity))",
          50: "rgb(var(--primary-50))",
          100: "rgb(var(--primary-100))",
          200: "rgb(var(--primary-200))",
          300: "rgb(var(--primary-300))",
          400: "rgb(var(--primary-400))",
          500: "rgb(var(--primary-500))",
          600: "rgb(var(--primary-600))",
          700: "rgb(var(--primary-700))",
          800: "rgb(var(--primary-800))",
          900: "rgb(var(--primary-900))",
          950: "rgb(var(--primary-950))",
        },
        secondary: {
          DEFAULT: "rgb(var(--secondary))",
          inverse: "rgb(var(--secondary-inverse))",
          hover: "rgb(var(--secondary-hover))",
          active: "rgb(var(--secondary-active-color))",
          highlight: "rgb(var(--secondary)/var(--secondary-highlight-opacity))",
          "highlight-inverse": "rgb(var(--secondary-highlight-inverse))",
          "highlight-hover":
            "rgb(var(--secondary)/var(--secondary-highlight-hover-opacity))",
          50: "rgb(var(--secondary-50))",
          100: "rgb(var(--secondary-100))",
          200: "rgb(var(--secondary-200))",
          300: "rgb(var(--secondary-300))",
          400: "rgb(var(--secondary-400))",
          500: "rgb(var(--secondary-500))",
          600: "rgb(var(--secondary-600))",
          700: "rgb(var(--secondary-700))",
          800: "rgb(var(--secondary-800))",
          900: "rgb(var(--secondary-900))",
          950: "rgb(var(--secondary-950))",
        },
        tertiary: {
          DEFAULT: "rgb(var(--tertiary))",
          inverse: "rgb(var(--tertiary-inverse))",
          hover: "rgb(var(--tertiary-hover))",
          active: "rgb(var(--tertiary-active-color))",
          highlight: "rgb(var(--tertiary)/var(--tertiary-highlight-opacity))",
          "highlight-inverse": "rgb(var(--tertiary-highlight-inverse))",
          "highlight-hover":
            "rgb(var(--tertiary)/var(--tertiary-highlight-hover-opacity))",
          50: "rgb(var(--tertiary-50))",
          100: "rgb(var(--tertiary-100))",
          200: "rgb(var(--tertiary-200))",
          300: "rgb(var(--tertiary-300))",
          400: "rgb(var(--tertiary-400))",
          500: "rgb(var(--tertiary-500))",
          600: "rgb(var(--tertiary-600))",
          700: "rgb(var(--tertiary-700))",
          800: "rgb(var(--tertiary-800))",
          900: "rgb(var(--tertiary-900))",
          950: "rgb(var(--tertiary-950))",
        },
        surface: {
          0: "rgb(var(--surface-0))",
          50: "rgb(var(--surface-50))",
          100: "rgb(var(--surface-100))",
          200: "rgb(var(--surface-200))",
          300: "rgb(var(--surface-300))",
          400: "rgb(var(--surface-400))",
          500: "rgb(var(--surface-500))",
          600: "rgb(var(--surface-600))",
          700: "rgb(var(--surface-700))",
          800: "rgb(var(--surface-800))",
          900: "rgb(var(--surface-900))",
          950: "rgb(var(--surface-950))",
        },
      },
    },
    fontFamily: {
      sans: [
        '"Inter"',
        "Lato",
        '"Helvetica Neue"',
        "Helvetica",
        "Arial",
        "sans-serif",
      ],
      body: [
        '"PT Sans"',
        "Nunito",
        "Lato",
        '"Helvetica Neue"',
        "Helvetica",
        "Arial",
        "sans-serif",
      ],
    },
  },
  plugins: [],
};
